// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3MGGIN4rEcrV00t0dRpvnYFslrHjiqk',
    appId: '1:803332171686:web:6a0a28fee59e5dac08d167',
    messagingSenderId: '803332171686',
    projectId: 'gamebox-a9c34',
    authDomain: 'gamebox-a9c34.firebaseapp.com',
    storageBucket: 'gamebox-a9c34.firebasestorage.app',
    measurementId: 'G-PB7SJGCJQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA07Eb4JMMbmrJOq8l2I0Bw8tTwFN5Gl0',
    appId: '1:803332171686:android:dff1f4bd944cad2d08d167',
    messagingSenderId: '803332171686',
    projectId: 'gamebox-a9c34',
    storageBucket: 'gamebox-a9c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ImH_OWGrXmYXJRHbZ6ssHFsbeXYCrQ4',
    appId: '1:803332171686:ios:03c8394b129ceb5208d167',
    messagingSenderId: '803332171686',
    projectId: 'gamebox-a9c34',
    storageBucket: 'gamebox-a9c34.firebasestorage.app',
    iosClientId: '803332171686-3mqkc91bo786esan1bui4b5lvtfmt31p.apps.googleusercontent.com',
    iosBundleId: 'com.qtilabs.gamebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ImH_OWGrXmYXJRHbZ6ssHFsbeXYCrQ4',
    appId: '1:803332171686:ios:03c8394b129ceb5208d167',
    messagingSenderId: '803332171686',
    projectId: 'gamebox-a9c34',
    storageBucket: 'gamebox-a9c34.firebasestorage.app',
    iosClientId: '803332171686-3mqkc91bo786esan1bui4b5lvtfmt31p.apps.googleusercontent.com',
    iosBundleId: 'com.qtilabs.gamebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3MGGIN4rEcrV00t0dRpvnYFslrHjiqk',
    appId: '1:803332171686:web:678dec4fc73d8bff08d167',
    messagingSenderId: '803332171686',
    projectId: 'gamebox-a9c34',
    authDomain: 'gamebox-a9c34.firebaseapp.com',
    storageBucket: 'gamebox-a9c34.firebasestorage.app',
    measurementId: 'G-MR8EWZG6H1',
  );
}
